server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/teacher/**