server:
  port: 8001
spring:
  application:
    name: user-service
eureka:
  client:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    wait-time-in-ms-when-sync-empty: 15000