server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/AaronSosaRamos/MicroservicesExample
          search-paths: config-data