server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: zipkin-micrometer
          uri: https://github.com/AaronSosaRamos/MicroservicesExample
          search-paths: config-data