server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/AaronSosaRamos/MicroservicesExample
          search-paths: config-data
          username: U20204320@gmail.com
          password: aArsaso_on273
          clone-on-start: true